name: Publish Typedoc to Github Pages
on:
  push:
    branches:
      - main
      - autogen-docs
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Create the docs directory locally in CI
        run: npx typedoc src/index.ts

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: autogen-docs
          folder: docs
